-- Update main categories to English
UPDATE categories SET name = 'AI Chat' WHERE id = 6;
UPDATE categories SET name = 'AI Writing' WHERE id = 1;
UPDATE categories SET name = 'AI Image' WHERE id = 31;
UPDATE categories SET name = 'AI Video' WHERE id = 25;
UPDATE categories SET name = 'AI Audio' WHERE id = 30;
UPDATE categories SET name = 'AI Code' WHERE id = 28;
UPDATE categories SET name = 'AI Search' WHERE id = 27;
UPDATE categories SET name = 'AI Translate' WHERE id = 32;
UPDATE categories SET name = 'AI Design' WHERE id = 29;
UPDATE categories SET name = 'AI Productivity' WHERE id = 24;

-- Update subcategories to English
UPDATE categories SET name = 'Copywriting' WHERE id = 39;
UPDATE categories SET name = 'Long Form Writing' WHERE id = 41;
UPDATE categories SET name = 'Rewriting' WHERE id = 40;
UPDATE categories SET name = 'Chat Assistant' WHERE id = 37;
UPDATE categories SET name = 'Role Play' WHERE id = 34;
UPDATE categories SET name = 'Customer Service' WHERE id = 36;
UPDATE categories SET name = 'Task Management' WHERE id = 59;
UPDATE categories SET name = 'Data Analysis' WHERE id = 57;
UPDATE categories SET name = 'Workflow Automation' WHERE id = 54;
UPDATE categories SET name = 'Video Generation' WHERE id = 53;
UPDATE categories SET name = 'Video Editing' WHERE id = 56;
UPDATE categories SET name = 'Animation' WHERE id = 58;
UPDATE categories SET name = 'Smart Search' WHERE id = 42;
UPDATE categories SET name = 'Q&A Systems' WHERE id = 45;
UPDATE categories SET name = 'Document Search' WHERE id = 44;
UPDATE categories SET name = 'Code Generation' WHERE id = 49;
UPDATE categories SET name = 'Code Review' WHERE id = 62;
UPDATE categories SET name = 'Debugging' WHERE id = 61;
UPDATE categories SET name = 'UI Design' WHERE id = 52;
UPDATE categories SET name = 'Logo Design' WHERE id = 50;
UPDATE categories SET name = 'Graphic Design' WHERE id = 51;
UPDATE categories SET name = 'Text to Speech' WHERE id = 60;
UPDATE categories SET name = 'Music Generation' WHERE id = 38;
UPDATE categories SET name = 'Audio Processing' WHERE id = 43;
UPDATE categories SET name = 'Text to Image' WHERE id = 35;
UPDATE categories SET name = 'Image to Image' WHERE id = 33;
UPDATE categories SET name = 'Image Editing' WHERE id = 55;
UPDATE categories SET name = 'Text Translation' WHERE id = 46;
UPDATE categories SET name = 'Real-time Translation' WHERE id = 48;
UPDATE categories SET name = 'Voice Translation' WHERE id = 47;